// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: guide/bolo.proto

package guide

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type WorldInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WorldInput) Reset() {
	*x = WorldInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldInput) ProtoMessage() {}

func (x *WorldInput) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldInput.ProtoReflect.Descriptor instead.
func (*WorldInput) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{0}
}

func (x *WorldInput) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WorldMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SizeH int32    `protobuf:"varint,1,opt,name=sizeH,proto3" json:"sizeH,omitempty"`
	SizeW int32    `protobuf:"varint,2,opt,name=sizeW,proto3" json:"sizeW,omitempty"`
	Tiles []string `protobuf:"bytes,3,rep,name=tiles,proto3" json:"tiles,omitempty"`
}

func (x *WorldMap) Reset() {
	*x = WorldMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldMap) ProtoMessage() {}

func (x *WorldMap) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldMap.ProtoReflect.Descriptor instead.
func (*WorldMap) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{1}
}

func (x *WorldMap) GetSizeH() int32 {
	if x != nil {
		return x.SizeH
	}
	return 0
}

func (x *WorldMap) GetSizeW() int32 {
	if x != nil {
		return x.SizeW
	}
	return 0
}

func (x *WorldMap) GetTiles() []string {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type WorldModification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Type   int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Health int32 `protobuf:"varint,4,opt,name=health,proto3" json:"health,omitempty"`
}

func (x *WorldModification) Reset() {
	*x = WorldModification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorldModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldModification) ProtoMessage() {}

func (x *WorldModification) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldModification.ProtoReflect.Descriptor instead.
func (*WorldModification) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{2}
}

func (x *WorldModification) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WorldModification) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WorldModification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WorldModification) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TankID int32  `protobuf:"varint,2,opt,name=tankID,proto3" json:"tankID,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{3}
}

func (x *Player) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetTankID() int32 {
	if x != nil {
		return x.TankID
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Tank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X  float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y  float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Tank) Reset() {
	*x = Tank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tank) ProtoMessage() {}

func (x *Tank) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tank.ProtoReflect.Descriptor instead.
func (*Tank) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{4}
}

func (x *Tank) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tank) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tank) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Writer string `protobuf:"bytes,2,opt,name=writer,proto3" json:"writer,omitempty"`
	Body   string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guide_bolo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_guide_bolo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_guide_bolo_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_guide_bolo_proto protoreflect.FileDescriptor

var file_guide_bolo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2f, 0x62, 0x6f, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x67, 0x75, 0x69, 0x64, 0x65, 0x22, 0x1c, 0x0a, 0x0a, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6c, 0x64,
	0x4d, 0x61, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x48, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x69, 0x7a,
	0x65, 0x57, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x57, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x11, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x22, 0x44, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x6e, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x74, 0x61,
	0x6e, 0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x61, 0x6e, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x45, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x32, 0xcb, 0x02, 0x0a, 0x04, 0x42, 0x6f, 0x6c, 0x6f, 0x12, 0x38, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x12, 0x11, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0x0d, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x22, 0x00, 0x30, 0x01, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x4d, 0x61, 0x70, 0x12, 0x11, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x57, 0x6f,
	0x72, 0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0f, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65,
	0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4d, 0x61, 0x70, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x11, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x57, 0x6f, 0x72,
	0x6c, 0x64, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x6e, 0x6b,
	0x73, 0x12, 0x11, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x0b, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x54, 0x61, 0x6e,
	0x6b, 0x22, 0x00, 0x30, 0x01, 0x12, 0x2c, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x61, 0x6e,
	0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0b, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x54, 0x61,
	0x6e, 0x6b, 0x1a, 0x0b, 0x2e, 0x67, 0x75, 0x69, 0x64, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x22,
	0x00, 0x28, 0x01, 0x12, 0x2c, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x0e, 0x2e, 0x67, 0x75,
	0x69, 0x64, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x67, 0x75,
	0x69, 0x64, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x74, 0x68, 0x61, 0x6e, 0x6d, 0x69, 0x6c, 0x2f, 0x62, 0x6f, 0x6c, 0x6f, 0x2f, 0x67, 0x75,
	0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guide_bolo_proto_rawDescOnce sync.Once
	file_guide_bolo_proto_rawDescData = file_guide_bolo_proto_rawDesc
)

func file_guide_bolo_proto_rawDescGZIP() []byte {
	file_guide_bolo_proto_rawDescOnce.Do(func() {
		file_guide_bolo_proto_rawDescData = protoimpl.X.CompressGZIP(file_guide_bolo_proto_rawDescData)
	})
	return file_guide_bolo_proto_rawDescData
}

var file_guide_bolo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_guide_bolo_proto_goTypes = []interface{}{
	(*WorldInput)(nil),        // 0: guide.WorldInput
	(*WorldMap)(nil),          // 1: guide.WorldMap
	(*WorldModification)(nil), // 2: guide.WorldModification
	(*Player)(nil),            // 3: guide.Player
	(*Tank)(nil),              // 4: guide.Tank
	(*Message)(nil),           // 5: guide.Message
}
var file_guide_bolo_proto_depIdxs = []int32{
	0, // 0: guide.Bolo.GetPlayersOnline:input_type -> guide.WorldInput
	0, // 1: guide.Bolo.GetWorldMap:input_type -> guide.WorldInput
	0, // 2: guide.Bolo.GetWorldModifications:input_type -> guide.WorldInput
	0, // 3: guide.Bolo.GetTanks:input_type -> guide.WorldInput
	4, // 4: guide.Bolo.SendTankData:input_type -> guide.Tank
	5, // 5: guide.Bolo.Chat:input_type -> guide.Message
	3, // 6: guide.Bolo.GetPlayersOnline:output_type -> guide.Player
	1, // 7: guide.Bolo.GetWorldMap:output_type -> guide.WorldMap
	2, // 8: guide.Bolo.GetWorldModifications:output_type -> guide.WorldModification
	4, // 9: guide.Bolo.GetTanks:output_type -> guide.Tank
	4, // 10: guide.Bolo.SendTankData:output_type -> guide.Tank
	5, // 11: guide.Bolo.Chat:output_type -> guide.Message
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guide_bolo_proto_init() }
func file_guide_bolo_proto_init() {
	if File_guide_bolo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_guide_bolo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_bolo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_bolo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorldModification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_bolo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_bolo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guide_bolo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guide_bolo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guide_bolo_proto_goTypes,
		DependencyIndexes: file_guide_bolo_proto_depIdxs,
		MessageInfos:      file_guide_bolo_proto_msgTypes,
	}.Build()
	File_guide_bolo_proto = out.File
	file_guide_bolo_proto_rawDesc = nil
	file_guide_bolo_proto_goTypes = nil
	file_guide_bolo_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BoloClient is the client API for Bolo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BoloClient interface {
	GetPlayersOnline(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetPlayersOnlineClient, error)
	GetWorldMap(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (*WorldMap, error)
	GetWorldModifications(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetWorldModificationsClient, error)
	GetTanks(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetTanksClient, error)
	SendTankData(ctx context.Context, opts ...grpc.CallOption) (Bolo_SendTankDataClient, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (Bolo_ChatClient, error)
}

type boloClient struct {
	cc grpc.ClientConnInterface
}

func NewBoloClient(cc grpc.ClientConnInterface) BoloClient {
	return &boloClient{cc}
}

func (c *boloClient) GetPlayersOnline(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetPlayersOnlineClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bolo_serviceDesc.Streams[0], "/guide.Bolo/GetPlayersOnline", opts...)
	if err != nil {
		return nil, err
	}
	x := &boloGetPlayersOnlineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bolo_GetPlayersOnlineClient interface {
	Recv() (*Player, error)
	grpc.ClientStream
}

type boloGetPlayersOnlineClient struct {
	grpc.ClientStream
}

func (x *boloGetPlayersOnlineClient) Recv() (*Player, error) {
	m := new(Player)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boloClient) GetWorldMap(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (*WorldMap, error) {
	out := new(WorldMap)
	err := c.cc.Invoke(ctx, "/guide.Bolo/GetWorldMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *boloClient) GetWorldModifications(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetWorldModificationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bolo_serviceDesc.Streams[1], "/guide.Bolo/GetWorldModifications", opts...)
	if err != nil {
		return nil, err
	}
	x := &boloGetWorldModificationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bolo_GetWorldModificationsClient interface {
	Recv() (*WorldModification, error)
	grpc.ClientStream
}

type boloGetWorldModificationsClient struct {
	grpc.ClientStream
}

func (x *boloGetWorldModificationsClient) Recv() (*WorldModification, error) {
	m := new(WorldModification)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boloClient) GetTanks(ctx context.Context, in *WorldInput, opts ...grpc.CallOption) (Bolo_GetTanksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bolo_serviceDesc.Streams[2], "/guide.Bolo/GetTanks", opts...)
	if err != nil {
		return nil, err
	}
	x := &boloGetTanksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Bolo_GetTanksClient interface {
	Recv() (*Tank, error)
	grpc.ClientStream
}

type boloGetTanksClient struct {
	grpc.ClientStream
}

func (x *boloGetTanksClient) Recv() (*Tank, error) {
	m := new(Tank)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boloClient) SendTankData(ctx context.Context, opts ...grpc.CallOption) (Bolo_SendTankDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bolo_serviceDesc.Streams[3], "/guide.Bolo/SendTankData", opts...)
	if err != nil {
		return nil, err
	}
	x := &boloSendTankDataClient{stream}
	return x, nil
}

type Bolo_SendTankDataClient interface {
	Send(*Tank) error
	CloseAndRecv() (*Tank, error)
	grpc.ClientStream
}

type boloSendTankDataClient struct {
	grpc.ClientStream
}

func (x *boloSendTankDataClient) Send(m *Tank) error {
	return x.ClientStream.SendMsg(m)
}

func (x *boloSendTankDataClient) CloseAndRecv() (*Tank, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Tank)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *boloClient) Chat(ctx context.Context, opts ...grpc.CallOption) (Bolo_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Bolo_serviceDesc.Streams[4], "/guide.Bolo/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &boloChatClient{stream}
	return x, nil
}

type Bolo_ChatClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type boloChatClient struct {
	grpc.ClientStream
}

func (x *boloChatClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *boloChatClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BoloServer is the server API for Bolo service.
type BoloServer interface {
	GetPlayersOnline(*WorldInput, Bolo_GetPlayersOnlineServer) error
	GetWorldMap(context.Context, *WorldInput) (*WorldMap, error)
	GetWorldModifications(*WorldInput, Bolo_GetWorldModificationsServer) error
	GetTanks(*WorldInput, Bolo_GetTanksServer) error
	SendTankData(Bolo_SendTankDataServer) error
	Chat(Bolo_ChatServer) error
}

// UnimplementedBoloServer can be embedded to have forward compatible implementations.
type UnimplementedBoloServer struct {
}

func (*UnimplementedBoloServer) GetPlayersOnline(*WorldInput, Bolo_GetPlayersOnlineServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPlayersOnline not implemented")
}
func (*UnimplementedBoloServer) GetWorldMap(context.Context, *WorldInput) (*WorldMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorldMap not implemented")
}
func (*UnimplementedBoloServer) GetWorldModifications(*WorldInput, Bolo_GetWorldModificationsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWorldModifications not implemented")
}
func (*UnimplementedBoloServer) GetTanks(*WorldInput, Bolo_GetTanksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTanks not implemented")
}
func (*UnimplementedBoloServer) SendTankData(Bolo_SendTankDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SendTankData not implemented")
}
func (*UnimplementedBoloServer) Chat(Bolo_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func RegisterBoloServer(s *grpc.Server, srv BoloServer) {
	s.RegisterService(&_Bolo_serviceDesc, srv)
}

func _Bolo_GetPlayersOnline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorldInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoloServer).GetPlayersOnline(m, &boloGetPlayersOnlineServer{stream})
}

type Bolo_GetPlayersOnlineServer interface {
	Send(*Player) error
	grpc.ServerStream
}

type boloGetPlayersOnlineServer struct {
	grpc.ServerStream
}

func (x *boloGetPlayersOnlineServer) Send(m *Player) error {
	return x.ServerStream.SendMsg(m)
}

func _Bolo_GetWorldMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorldInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BoloServer).GetWorldMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/guide.Bolo/GetWorldMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BoloServer).GetWorldMap(ctx, req.(*WorldInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bolo_GetWorldModifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorldInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoloServer).GetWorldModifications(m, &boloGetWorldModificationsServer{stream})
}

type Bolo_GetWorldModificationsServer interface {
	Send(*WorldModification) error
	grpc.ServerStream
}

type boloGetWorldModificationsServer struct {
	grpc.ServerStream
}

func (x *boloGetWorldModificationsServer) Send(m *WorldModification) error {
	return x.ServerStream.SendMsg(m)
}

func _Bolo_GetTanks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorldInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BoloServer).GetTanks(m, &boloGetTanksServer{stream})
}

type Bolo_GetTanksServer interface {
	Send(*Tank) error
	grpc.ServerStream
}

type boloGetTanksServer struct {
	grpc.ServerStream
}

func (x *boloGetTanksServer) Send(m *Tank) error {
	return x.ServerStream.SendMsg(m)
}

func _Bolo_SendTankData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoloServer).SendTankData(&boloSendTankDataServer{stream})
}

type Bolo_SendTankDataServer interface {
	SendAndClose(*Tank) error
	Recv() (*Tank, error)
	grpc.ServerStream
}

type boloSendTankDataServer struct {
	grpc.ServerStream
}

func (x *boloSendTankDataServer) SendAndClose(m *Tank) error {
	return x.ServerStream.SendMsg(m)
}

func (x *boloSendTankDataServer) Recv() (*Tank, error) {
	m := new(Tank)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Bolo_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BoloServer).Chat(&boloChatServer{stream})
}

type Bolo_ChatServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type boloChatServer struct {
	grpc.ServerStream
}

func (x *boloChatServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *boloChatServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Bolo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "guide.Bolo",
	HandlerType: (*BoloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorldMap",
			Handler:    _Bolo_GetWorldMap_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPlayersOnline",
			Handler:       _Bolo_GetPlayersOnline_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetWorldModifications",
			Handler:       _Bolo_GetWorldModifications_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetTanks",
			Handler:       _Bolo_GetTanks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendTankData",
			Handler:       _Bolo_SendTankData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _Bolo_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "guide/bolo.proto",
}
